// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9daKNNRFMKf5P5DkhgoEEVh_6LmProec',
    appId: '1:202140480066:web:53e17eedcf647a4bb3f3db',
    messagingSenderId: '202140480066',
    projectId: 'mentorconnect-2fe91',
    authDomain: 'mentorconnect-2fe91.firebaseapp.com',
    storageBucket: 'mentorconnect-2fe91.appspot.com',
    measurementId: 'G-GJKEZ7L2ZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf3CtFtBDa7OJcruIdCm8-hjPEZ30K-aY',
    appId: '1:202140480066:android:1a2150933c37eeffb3f3db',
    messagingSenderId: '202140480066',
    projectId: 'mentorconnect-2fe91',
    storageBucket: 'mentorconnect-2fe91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDn-SiFpPlmZnKsJNWFM0Do9UmZmDIr2g',
    appId: '1:202140480066:ios:1b38f14b140a86adb3f3db',
    messagingSenderId: '202140480066',
    projectId: 'mentorconnect-2fe91',
    storageBucket: 'mentorconnect-2fe91.appspot.com',
    iosBundleId: 'com.example.mentorconnect',
  );
}
